# Generated by Django 4.2.20 on 2025-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vitamins', 'Vitamins'), ('protein', 'Protein'), ('meal_subs', 'Meal Substitutes'), ('collagen', 'Collagen'), ('accessories', 'Accessories')], default='vitamins', max_length=20),
            preserve_default=False,
        ),
    ]
