# Generated by Django 4.2.20 on 2025-04-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_ingredients_product_reviews_product_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='usage',
            new_name='valeur_nutritive',
        ),
    ]
