# Generated by Django 4.2.20 on 2025-04-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_usage_product_valeur_nutritive'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='utilisation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
