# Generated by Django 4.2.20 on 2025-05-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_price_product_base_price_product_has_variants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='base_price',
            new_name='price',
        ),
    ]
